### ISSUE TITLE
Shovel Tag

### ISSUE THREAD

**Issue by SubstrateBruh** [pnk2u/More-Tool-Variants#1]
The variant shovels are not tagged properly. I am not sure of the full consequences of this, but I initially noticed a problem through not being able to enchant any variant shovels.

**Comment by SubstrateBruh** [comment]
I just noticed your most recent push, and investigated some more.
I inspected the tags with REI, and the other tools are properly marked with #minecraft:hoes, #minecraft:pickaxes, Etc.
The shovels however are only marked with #mstv-mtool:variant_shovels.
Wooden shovels are properly marked as fuel.

**Comment by pnk2u** [comment]
Hi, thanks for finding this and letting me know, it was in fact a silly mistake where I added variant_axes to the vanilla shovel tag instead of variant_shovels. It is fixed in version 1.0.2. (:
